export const CURSOS = [
  {
    id: 'c1',
    slug: 'transparencia-rendicion-cuentas',
    titulo: 'Transparencia y Rendición de Cuentas',
    descripcion:
      'Marco normativo, obligaciones y mejores prácticas para servidores públicos en materia de transparencia.',
    duracion: '6h 20min',
    lecciones: 18,
    modulos: 5,
    nivel: 'Fundamental',
    instructor: 'Dra. Alejandra Rueda',
    instructor_cargo: 'Dirección de Capacitación',
    imagen: 'Archivos abiertos',
    inscritos: 1247,
    progreso: 0.42,
  },
  {
    id: 'c2',
    slug: 'gestion-documental',
    titulo: 'Gestión Documental en la Administración Pública',
    descripcion:
      'Ciclo de vida de los documentos institucionales, archivos de trámite y archivo de concentración.',
    duracion: '4h 45min',
    lecciones: 12,
    modulos: 4,
    nivel: 'Intermedio',
    instructor: 'Mtro. Fernando Caamal',
    instructor_cargo: 'Coordinación de Archivo',
    imagen: 'Expedientes',
    inscritos: 892,
    progreso: 1.0,
  },
  {
    id: 'c3',
    slug: 'prevencion-conflicto-intereses',
    titulo: 'Prevención de Conflicto de Intereses',
    descripcion:
      'Identificación, declaración y resolución de situaciones de conflicto en el ejercicio público.',
    duracion: '3h 10min',
    lecciones: 9,
    modulos: 3,
    nivel: 'Fundamental',
    instructor: 'Lic. Marisol Peña',
    instructor_cargo: 'Contraloría Interna',
    imagen: 'Balance',
    inscritos: 2104,
    progreso: 0,
  },
  {
    id: 'c4',
    slug: 'presupuesto-base-cero',
    titulo: 'Presupuesto Base Cero para Unidades Administrativas',
    descripcion:
      'Metodología, estructuras programáticas y defensa presupuestal ante autoridades hacendarias.',
    duracion: '8h 15min',
    lecciones: 22,
    modulos: 6,
    nivel: 'Avanzado',
    instructor: 'Dr. Ricardo Lomelí',
    instructor_cargo: 'Dirección de Finanzas',
    imagen: 'Cifras',
    inscritos: 518,
    progreso: 0.18,
  },
  {
    id: 'c5',
    slug: 'atencion-ciudadana',
    titulo: 'Atención Ciudadana y Trato Digno',
    descripcion:
      'Protocolos de atención, lenguaje incluyente y resolución de quejas en ventanilla y en línea.',
    duracion: '2h 50min',
    lecciones: 8,
    modulos: 3,
    nivel: 'Fundamental',
    instructor: 'Lic. Ximena Treviño',
    instructor_cargo: 'Bienestar Institucional',
    imagen: 'Ventanilla',
    inscritos: 3401,
    progreso: 0.66,
  },
  {
    id: 'c6',
    slug: 'firma-electronica-tramites',
    titulo: 'Firma Electrónica y Trámites Digitales',
    descripcion: 'e.firma, sellos digitales y expediente electrónico en trámites gubernamentales.',
    duracion: '3h 30min',
    lecciones: 10,
    modulos: 4,
    nivel: 'Intermedio',
    instructor: 'Ing. Paulo Sandoval',
    instructor_cargo: 'Dirección de Tecnología',
    imagen: 'Firma digital',
    inscritos: 1876,
    progreso: 0,
  },
]

export const MODULOS_CURSO = [
  {
    id: 'm1',
    orden: 1,
    titulo: 'Fundamentos de la transparencia',
    descripcion:
      'Marco constitucional y legal que da sustento al derecho de acceso a la información pública.',
    duracion: '58 min',
    lecciones_count: 4,
    completado: 1.0,
    requiere_previo: false,
  },
  {
    id: 'm2',
    orden: 2,
    titulo: 'Sujetos obligados y obligaciones de oficio',
    descripcion:
      'Quiénes son sujetos obligados, qué información deben publicar y con qué periodicidad.',
    duracion: '1h 12min',
    lecciones_count: 5,
    completado: 0.6,
    requiere_previo: true,
  },
  {
    id: 'm3',
    orden: 3,
    titulo: 'Clasificación de la información',
    descripcion: 'Reservada, confidencial, pública. Pruebas de daño e interés público.',
    duracion: '1h 05min',
    lecciones_count: 4,
    completado: 0,
    requiere_previo: true,
  },
  {
    id: 'm4',
    orden: 4,
    titulo: 'Procedimiento de acceso a la información',
    descripcion:
      'Del ingreso de la solicitud a la respuesta. Plazos, prórrogas y recursos de revisión.',
    duracion: '1h 30min',
    lecciones_count: 3,
    completado: 0,
    requiere_previo: true,
  },
  {
    id: 'm5',
    orden: 5,
    titulo: 'Casos prácticos y evaluación final',
    descripcion: 'Ejercicios aplicados y examen para constancia.',
    duracion: '45 min',
    lecciones_count: 2,
    completado: 0,
    requiere_previo: true,
  },
]

export const LECCIONES_MODULO = [
  {
    id: 'l1',
    orden: 1,
    titulo: '¿Qué es la transparencia proactiva?',
    duracion: '11:24',
    completado: true,
    tipo: 'video',
  },
  {
    id: 'l2',
    orden: 2,
    titulo: 'Obligaciones comunes (Art. 70 LGTAIP)',
    duracion: '14:08',
    completado: true,
    tipo: 'video',
  },
  {
    id: 'l3',
    orden: 3,
    titulo: 'Obligaciones específicas por sujeto',
    duracion: '16:42',
    completado: true,
    tipo: 'video',
  },
  {
    id: 'l4',
    orden: 4,
    titulo: 'Plataforma Nacional de Transparencia',
    duracion: '12:15',
    completado: false,
    tipo: 'video',
    actual: true,
  },
  {
    id: 'l5',
    orden: 5,
    titulo: 'Lectura complementaria',
    duracion: '8 min',
    completado: false,
    tipo: 'lectura',
  },
]

export const COMENTARIOS_INICIALES = [
  {
    id: 1,
    user: 'Ana Lucía M.',
    dep: 'SRE',
    t: 'hace 2 min',
    texto: 'La explicación del Art. 70 está clarísima. Acabo de tomar nota.',
  },
  {
    id: 2,
    user: 'Jorge Hdz.',
    dep: 'SEMARNAT',
    t: 'hace 3 min',
    texto: '¿Alguien sabe si esto aplica también a fideicomisos privados?',
  },
  {
    id: 3,
    user: 'Patricia N.',
    dep: 'IMSS',
    t: 'hace 4 min',
    texto: 'En mi unidad publicamos mensualmente. Pensé que era trimestral.',
  },
  {
    id: 4,
    user: 'Carlos E.',
    dep: 'SEDATU',
    t: 'hace 5 min',
    texto: 'Gracias por el recurso de la PNT, lo compartí con mi equipo.',
  },
  {
    id: 5,
    user: 'Daniela R.',
    dep: 'INE',
    t: 'hace 6 min',
    texto: 'Recordar: las obligaciones específicas varían por tipo de sujeto obligado.',
  },
]

export const COMENTARIOS_FUENTE = [
  { user: 'Beatriz T.', dep: 'SECTUR', texto: 'Excelente punto sobre la clasificación.' },
  {
    user: 'Raúl M.',
    dep: 'CULTURA',
    texto: '¿El examen final también se hace por esta plataforma?',
  },
  {
    user: 'Lizbeth A.',
    dep: 'STPS',
    texto: 'Estoy tomando este curso por tercera vez y sigo aprendiendo cosas.',
  },
  {
    user: 'Mario V.',
    dep: 'SEDENA',
    texto: 'Pregunta: ¿la constancia se descarga al terminar o llega por correo?',
  },
  { user: 'Fernanda C.', dep: 'BIENESTAR', texto: 'Muy buen contenido, gracias Dra. Rueda.' },
  {
    user: 'Óscar P.',
    dep: 'SCT',
    texto: 'Anotando: plazos de respuesta 20 días hábiles, prórroga hasta 10 más.',
  },
  {
    user: 'Adriana L.',
    dep: 'SALUD',
    texto: 'Compañeros, recuerden que mañana hay sesión en vivo de Q&A.',
  },
  { user: 'Emilio G.', dep: 'SHCP', texto: 'El caso práctico del módulo 5 es súper útil.' },
  { user: 'Regina D.', dep: 'SEP', texto: 'Alguien más desde educación? Saludos!' },
  {
    user: 'Hugo R.',
    dep: 'PEMEX',
    texto: 'La distinción entre reservada y confidencial me quedaba confusa, ya no.',
  },
  {
    user: 'Valentina S.',
    dep: 'CFE',
    texto: 'Me encantaría ver este curso replicado para el personal operativo.',
  },
  {
    user: 'Tomás N.',
    dep: 'FGR',
    texto: 'Dato: los recursos de revisión se tramitan ante el INAI.',
  },
]

export const DEPENDENCIAS = [
  'Dirección General',
  'Recursos Humanos',
  'Finanzas',
  'Tecnologías de la Información',
  'Jurídico',
  'Comunicación',
  'Operaciones',
  'Otra área',
]

export const USER = {
  nombre: 'María Fernanda',
  apellidos: 'Escalante Ríos',
  correo: 'mf.escalante@example.org',
  telefono: '55 1234 5678',
  dependencia: 'Dirección de Finanzas',
  iniciales: 'MF',
  cursos_activos: 3,
  cursos_completados: 2,
  horas: 18.5,
  constancias: 2,
}
