-- Migration 037: Sistema de rúbricas — ANULADA
-- =========================================================================
-- Esta migración nunca se aplicó en ninguna instalación: fallaba al primer
-- statement. Se conserva el archivo (y su nombre en public._migraciones)
-- pero su contenido se anula deliberadamente. Motivos:
--
--   1. Referenciaba `public.evaluaciones` y `public.resultados_evaluacion`,
--      tablas que no existen ni han existido en este esquema.
--   2. Sus políticas usaban `perfiles.rol = 'admin'`; la columna es
--      `perfiles.es_admin` (boolean). Ver public.is_admin() en 006.
--   3. Usaba `numnonnulls(...)`; la función es `num_nonnulls(...)`.
--   4. Lo decisivo: creaba `public.rubricas` con forma
--      (nombre, descripcion, criterios jsonb) INCOMPATIBLE con la que crea
--      053_entregas_rubricas.sql (tarea_id, tipo, titulo, puntaje_maximo),
--      que es la que usa el cliente (src/services/rubricas.ts). Como 053
--      declara `create table if not exists`, aplicar 037 dejaría el esquema
--      equivocado en pie SIN error, y todas las rúbricas dejarían de
--      funcionar de forma silenciosa.
--
-- El modelo de rúbricas vigente es el de 053: rubricas + rubrica_criterios
-- + rubrica_niveles. No añadir nada aquí.
-- =========================================================================

select 1;
